name: numchat
description: "NumChat - Chat on WhatsApp without saving numbers."
publish_to: 'none'

version: 1.0.6+6

environment:
  sdk: ^3.6.0

dependencies:
  country_code_picker: ^3.1.0
  fl_country_code_picker: ^0.1.9
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.6.0
  custom_lint: ^0.7.0
  custom_lint_builder: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_assets:
  assets_path: assets/images/
  output_path: lib/Core
  filename: 'image_assets.dart'
  field_prefix: null

